### ISSUE TITLE
Failed to start in production build.

### ISSUE THREAD

**Issue by mzch** [ricci2511/openkban#1]
When `npm run build && npm start`, the following error happens:

```
Authentication providers failed to load :(
```

When `npm run dev`, no error.

Could you tell me how to fix this issue?

**Comment by ricci2511** [comment]
I implemented a workaround for it with my latest commit. It's some weird issue on next auth's side that prevents fetching the auth providers api during build time, but it should work now.
Today I've done quite a few changes since you opened this issue, so I would recommend pulling all the latest commits and rerunning the docker compose file (also take a look into the .env.example).

**Comment by mzch** [comment]
Great! Thanks @ricci2511 ! :)
